"""empty message

Revision ID: dbfa80d7b316
Revises: 
Create Date: 2020-12-02 22:36:04.426034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfa80d7b316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrap', sa.Column('recipeClass', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrap', 'recipeClass')
    # ### end Alembic commands ###
